[listen]
server="127.0.0.1:8090"

[admin]
username="root"
password="111111"

[log.console]
level="debug"
color=true
jsonFormat=false
format=""

[log.file]
level="debug"
filename="log/fastgo.log"
maxSize=1048576
maxLine=1000000
dateSlice="d"
jsonFormat=true
format=""
[log.file.levelFilename]
error="log/error.log"
info="log/info.log"

[session]

